In [99]:
import pandas as pd 
import numpy as np

In [100]:
# Read data and clean data
data = pd.read_csv('final_data.csv', encoding = "CP949")
data = pd.DataFrame(data)
data = data.drop(['Unnamed: 0'], axis = 1)
print(data.head())
print(data.tail())

   경기도남양주시진접읍84  경기도화성시반송동84  경기도화성시봉담읍84  경기도남양주시호평동84  경기도화성시향남읍84  \
0    23679.8947   37084.3750   20734.3750    25632.5000   22607.8947   
1    21847.3333   36286.3636   22288.8824    24075.0000   22393.4783   
2    21751.0968   34916.0714   21576.2500    24533.0000   22645.4545   
3    22952.8049   35281.0811   21809.5000    24554.3226   22978.1250   
4    23099.4926   36368.5294   23075.0455    24375.4545   22335.1951   

   경기도남양주시화도읍84  경기도김포시장기동84  서울특별시송파구잠실동84  서울특별시동작구상도동84  서울특별시강북구미아동84  \
0    20413.1579   30160.0000     86395.6522     49950.0000     33980.0000   
1    21035.0000   26778.5714     82995.0000     47381.2500     35546.1538   
2    20011.7647   29259.2000     84577.5000     49237.5000     35300.0000   
3    20214.2857   28455.7143     84844.6809     49454.1667     31394.4444   
4    20951.4706   30735.6522     85905.7377     55062.1852     32445.8333   

   ...  경기도용인기흥구청덕동84  경기도김포시풍무동84  경기도남양주시오남읍59  서울특별시중랑구신내동84  경기도평택시포승읍59  \
0  ...     26650.0000   

In [101]:
# Use first 6 assets and split data into 70% train data and 30% test data
# 'Geyonggi, Hwaseong, Cheongye-dong' has no contract about first 3 years, so cubicspline works not properly.
data = data.iloc[:, :6]

train_data = data.iloc[:84, :]
test_data = data.iloc[84:, :]
print(train_data.head())
print(test_data.head())

   경기도남양주시진접읍84  경기도화성시반송동84  경기도화성시봉담읍84  경기도남양주시호평동84  경기도화성시향남읍84  \
0    23679.8947   37084.3750   20734.3750    25632.5000   22607.8947   
1    21847.3333   36286.3636   22288.8824    24075.0000   22393.4783   
2    21751.0968   34916.0714   21576.2500    24533.0000   22645.4545   
3    22952.8049   35281.0811   21809.5000    24554.3226   22978.1250   
4    23099.4926   36368.5294   23075.0455    24375.4545   22335.1951   

   경기도남양주시화도읍84  
0    20413.1579  
1    21035.0000  
2    20011.7647  
3    20214.2857  
4    20951.4706  
    경기도남양주시진접읍84  경기도화성시반송동84  경기도화성시봉담읍84  경기도남양주시호평동84  경기도화성시향남읍84  \
84    28281.4815   41628.8000   23401.8519    28242.1053   24562.5000   
85    28391.1765   42962.8571   22767.0732    28183.3333   23976.7857   
86    28764.5161   43739.5000   24052.8571    29339.3939   24313.4615   
87    29745.1250   44037.1795   25175.6410    29346.8750   24514.7059   
88    27933.0000   44150.7937   24551.3158    29794.8980   24309.2593   

    경기도남양주시화도읍84  
8

In [102]:
from scipy.interpolate import CubicSpline
import matplotlib.pyplot as plt

In [103]:
# Apply cubicspline to NA imputation
for i in range(6): 
    cs = train_data.iloc[:, i].dropna()
    idx = cs.index.tolist()
    cs = cs.tolist()
    cs = CubicSpline(idx, cs, bc_type='natural')
    train_data.iloc[:, i] = cs(np.arange(84))

print(train_data)

    경기도남양주시진접읍84  경기도화성시반송동84  경기도화성시봉담읍84  경기도남양주시호평동84  경기도화성시향남읍84  \
0     23679.8947   37084.3750   20734.3750    25632.5000   22607.8947   
1     21847.3333   36286.3636   22288.8824    24075.0000   22393.4783   
2     21751.0968   34916.0714   21576.2500    24533.0000   22645.4545   
3     22952.8049   35281.0811   21809.5000    24554.3226   22978.1250   
4     23099.4926   36368.5294   23075.0455    24375.4545   22335.1951   
..           ...          ...          ...           ...          ...   
79    28048.5294   40006.5000   24605.2632    29598.1481   23978.5246   
80    26977.5862   40833.3333   24275.0000    30338.4615   24491.2121   
81    28294.2308   42480.0000   23643.0769    28886.3636   25083.3333   
82    26847.1429   41684.2105   23084.7826    27995.8333   23954.7059   
83    28401.5625   42483.3333   23405.1282    27717.8571   24392.0000   

    경기도남양주시화도읍84  
0     20413.1579  
1     21035.0000  
2     20011.7647  
3     20214.2857  
4     20951.4706  
..       

C:\Users\Jaeyong\anaconda3\lib\site-packages\pandas\core\indexing.py:1843: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [104]:
train_data_array=np.array(train_data)
print(train_data_array)

# return matrix
r=np.ndarray((83,6))

[[23679.89473684 37084.375      20734.375      25632.5
  22607.89473684 20413.15789474]
 [21847.33333333 36286.36363636 22288.88235294 24075.
  22393.47826087 21035.        ]
 [21751.09677419 34916.07142857 21576.25       24533.
  22645.45454545 20011.76470588]
 [22952.80487805 35281.08108108 21809.5        24554.32258065
  22978.125      20214.28571429]
 [23099.49264706 36368.52941176 23075.04545455 24375.45454545
  22335.19512195 20951.47058824]
 [23357.84090909 35705.17241379 22106.08333333 24690.78378378
  23210.22727273 20730.43478261]
 [23197.35849057 35274.59459459 22642.82352941 25006.25
  22520.375      21001.92307692]
 [22653.84615385 35862.5        22367.35714286 24547.875
  23311.11111111 22210.71428571]
 [22223.68421053 34060.52631579 21961.46875    24744.44444444
  23067.90322581 21119.64285714]
 [22577.         34831.66666667 21709.12121212 24719.51219512
  22136.06896552 20420.55555556]
 [22512.68656716 34920.45454545 21746.875      24232.14285714
  22194.6969697  20903

In [105]:
# calculate return
# Applied ** 12 for each return to make the return as annual return.
for i in range(r.shape[1]): 
    r[:, i] = ((train_data_array[1:84, i] / train_data_array[0:83, i]) ** 12 ) - 1 
print(r)

[[-6.19614451e-01 -2.29753359e-01  1.38104781e+00 -5.28692927e-01
  -1.08056804e-01  4.33467524e-01]
 [-5.15974597e-02 -3.69938275e-01 -3.22901138e-01  2.53754072e-01
   1.43704534e-01 -4.50314275e-01]
 [ 9.06580950e-01  1.32917101e-01  1.37724009e-01  1.04796661e-02
   1.91248984e-01  1.28433949e-01]
 [ 7.94440025e-02  4.39482115e-01  9.67715346e-01 -8.39963765e-02
  -2.88619497e-01  5.36998137e-01]
 [ 1.42781125e-01 -1.98202441e-01 -4.02372117e-01  1.66771575e-01
   5.85899661e-01 -1.19505212e-01]
 [-7.94019391e-02 -1.35488530e-01  3.33599266e-01  1.64566540e-01
  -3.03766849e-01  1.68982025e-01]
 [-2.47613573e-01  2.19389247e-01 -1.36605883e-01 -1.99089452e-01
   5.13032573e-01  9.57228558e-01]
 [-2.05508371e-01 -4.61321652e-01 -1.97286599e-01  1.00438189e-01
  -1.18257536e-01 -4.53627878e-01]
 [ 2.08376048e-01  3.08202011e-01 -1.29496861e-01 -1.20242962e-02
  -3.90310746e-01 -3.32314722e-01]
 [-3.36529986e-02  3.10211876e-02  2.10696697e-02 -2.12549810e-01
   3.22494212e-02  3.2389

In [106]:
# Adjusted returns to account for current prices

price = train_data_array[train_data_array.shape[0]-1,:]
adj = price / np.mean(price)
r_adj = r * adj
print(r_adj)

[[-6.24607319e-01 -3.46436588e-01  1.14726313e+00 -5.20123468e-01
  -9.35497923e-02  3.48430724e-01]
 [-5.20132332e-02 -5.57816234e-01 -2.68240220e-01  2.49641032e-01
   1.24411687e-01 -3.61972513e-01]
 [ 9.13886200e-01  2.00420777e-01  1.14409998e-01  1.03098037e-02
   1.65573125e-01  1.03238031e-01]
 [ 8.00841641e-02  6.62678816e-01  8.03899854e-01 -8.26348990e-02
  -2.49871298e-01  4.31650906e-01]
 [ 1.43931659e-01 -2.98862125e-01 -3.34258300e-01  1.64068414e-01
   5.07240539e-01 -9.60609164e-02]
 [-8.00417617e-02 -2.04298141e-01  2.77127362e-01  1.61899120e-01
  -2.62985064e-01  1.35831466e-01]
 [-2.49608848e-01  3.30808926e-01 -1.13481149e-01 -1.95862458e-01
   4.44156118e-01  7.69441356e-01]
 [-2.07164362e-01 -6.95609846e-01 -1.63889793e-01  9.88102097e-02
  -1.02381039e-01 -3.64636059e-01]
 [ 2.10055147e-01  4.64726406e-01 -1.07575547e-01 -1.18293973e-02
  -3.37910134e-01 -2.67121878e-01]
 [-3.39241753e-02  4.67757008e-02  1.75029821e-02 -2.09104640e-01
   2.79198212e-02  2.6035

In [107]:
# Calculate return and covariance matrix for training data
mu = np.mean(r_adj,axis = 0)
sigma = np.cov(r_adj.T)

In [108]:
print(mu)

[0.11140197 0.09647029 0.07731924 0.07104768 0.05040973 0.12074455]


In [109]:
print(sigma)

[[ 0.19058299  0.05754072 -0.00293819  0.00600126  0.01083507 -0.04702808]
 [ 0.05754072  0.22245443  0.03711413 -0.01211019 -0.00709406 -0.03075613]
 [-0.00293819  0.03711413  0.12424921  0.02968338 -0.01820187  0.00782663]
 [ 0.00600126 -0.01211019  0.02968338  0.14948229  0.01364413 -0.05016642]
 [ 0.01083507 -0.00709406 -0.01820187  0.01364413  0.0815112  -0.01607576]
 [-0.04702808 -0.03075613  0.00782663 -0.05016642 -0.01607576  0.31012103]]


In [110]:
from qiskit import Aer
from qiskit.algorithms import VQE, QAOA, NumPyMinimumEigensolver
from qiskit.algorithms.optimizers import COBYLA
from qiskit.circuit.library import TwoLocal
from qiskit.utils import QuantumInstance
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit_optimization.applications import OptimizationApplication
from qiskit_optimization.converters import QuadraticProgramToQubo
import qiskit_optimization
import numpy as np
import matplotlib.pyplot as plt
import datetime

In [111]:
# Set number of assets and risk appetite

num = 6
q = 0.5

In [112]:
# Code to display results

def index_to_selection2(i, num_assets):
    s = "{0:b}".format(i).rjust(num_assets * 2)
    x = np.array([1 if s[i] == "1" else 0 for i in reversed(range(num_assets * 2))])
    return x

In [113]:
# Code to display results

def print_result2(result, problem):
    selection = result.x
    value = result.fval
    print("Optimal: selection {}, value {:.4f}".format(selection, value))
    
    list_a = list(result.min_eigen_solver_result.eigenstate.keys())
    selection = np.ndarray(np.size(list_a))
    value = np.ndarray(np.size(list_a))
    for i in range(np.size(list_a)):
        value[i] = QuadraticProgramToQubo().convert(problem).objective.evaluate(index_to_selection2(int(list_a[i],2),num))
        selection[i] = list_a[i][::-1]
    probabilities = np.square(list(result.min_eigen_solver_result.eigenstate.values()))
    
    d = {'selection': selection, 'value': value, 'prob':probabilities}
    df = pd.DataFrame(d)
    df_sorted = df.sort_values(by = 'prob',ascending = False)
    
    print("\n----------------- Full result ---------------------")
    print(df_sorted.head(10))

In [114]:
# Quadratic problem for '0, 1, or 2' assets available (Problem 2, Training data)
qp2 = qiskit_optimization.QuadraticProgram()
for i in range(6): 
    name = "x_" + str(i)
    qp2.integer_var(lowerbound=0, upperbound=2, name=name)

qp2.minimize(quadratic = q * sigma, linear = -1 * mu)
print(qp2.export_as_lp_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: CPLEX

Minimize
 obj: - 0.111401971254 x_0 - 0.096470293894 x_1 - 0.077319244025 x_2
      - 0.071047677340 x_3 - 0.050409729773 x_4 - 0.120744546605 x_5 + [
      0.190582991451 x_0^2 + 0.115081443944 x_0*x_1 - 0.005876372512 x_0*x_2
      + 0.012002518106 x_0*x_3 + 0.021670146828 x_0*x_4 - 0.094056161178 x_0*x_5
      + 0.222454433080 x_1^2 + 0.074228258467 x_1*x_2 - 0.024220386390 x_1*x_3
      - 0.014188119424 x_1*x_4 - 0.061512251906 x_1*x_5 + 0.124249207446 x_2^2
      + 0.059366763870 x_2*x_3 - 0.036403730514 x_2*x_4 + 0.015653263482 x_2*x_5
      + 0.149482291718 x_3^2 + 0.027288259061 x_3*x_4 - 0.100332833638 x_3*x_5
      + 0.081511201905 x_4^2 - 0.032151525039 x_4*x_5 + 0.310121028387 x_5^2 ]/2
Subject To

Bounds
       x_0 <= 2
       x_1 <= 2
       x_2 <= 2
       x_3 <= 2
       x_4 <= 2
       x_5 <= 2

Generals
 x_0 x_1 x_2 x_3 x_4 x_5
End



In [115]:
from qiskit_optimization.converters import IntegerToBinary

# Change discrete optimization problem to binary problem (Problem 2, Training data)
ineq2eq = IntegerToBinary()
qp2_eq = ineq2eq.convert(qp2)
print(qp2_eq.export_as_lp_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: CPLEX

Minimize
 obj: - 0.111401971254 x_0@0 - 0.111401971254 x_0@1 - 0.096470293894 x_1@0
      - 0.096470293894 x_1@1 - 0.077319244025 x_2@0 - 0.077319244025 x_2@1
      - 0.071047677340 x_3@0 - 0.071047677340 x_3@1 - 0.050409729773 x_4@0
      - 0.050409729773 x_4@1 - 0.120744546605 x_5@0 - 0.120744546605 x_5@1 + [
      0.190582991451 x_0@0^2 + 0.381165982903 x_0@0*x_0@1
      + 0.115081443944 x_0@0*x_1@0 + 0.115081443944 x_0@0*x_1@1
      - 0.005876372512 x_0@0*x_2@0 - 0.005876372512 x_0@0*x_2@1
      + 0.012002518106 x_0@0*x_3@0 + 0.012002518106 x_0@0*x_3@1
      + 0.021670146828 x_0@0*x_4@0 + 0.021670146828 x_0@0*x_4@1
      - 0.094056161178 x_0@0*x_5@0 - 0.094056161178 x_0@0*x_5@1
      + 0.190582991451 x_0@1^2 + 0.115081443944 x_0@1*x_1@0
      + 0.115081443944 x_0@1*x_1@1 - 0.005876372512 x_0@1*x_2@0
      - 0.005876372512 x_0@1*x_2@1 + 0.012002518106 x_0@1*x_3@0
      + 0.012002518106 x_0@1*x_3@1 

In [121]:
# Result of discrete(0, 1, 2) quadratic problem with qasm simulator and QAOA (Problem 2, Training data)
backend = Aer.get_backend("qasm_simulator")

cobyla = COBYLA()
cobyla.set_options(maxiter=250)
quantum_instance = QuantumInstance(backend=backend)
qaoa_mes = QAOA(optimizer=cobyla, reps=10, quantum_instance=quantum_instance)
qaoa = MinimumEigenOptimizer(qaoa_mes)
result_prob2 = qaoa.solve(qp2_eq)

print(result_prob2)

optimal function value: -0.07222546652860223
optimal value: [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0.]
status: SUCCESS


In [122]:
# Result for QAOA (Problem 2, Training data)

print_result2(result_prob2, qp2_eq)

Optimal: selection [1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0.], value -0.0722

----------------- Full result ---------------------
            selection   value   prob
139     10010100.0000  0.0040 0.0049
251  10000001010.0000 -0.0437 0.0049
146  10001010100.0000  0.0018 0.0049
588    101000101.0000 -0.0030 0.0049
328 100001000110.0000 -0.0722 0.0039
67        101000.0000  0.0077 0.0039
526    110101001.0000 -0.0182 0.0039
546 100100011001.0000 -0.0482 0.0039
362 100000010110.0000 -0.0705 0.0039
708 110000011011.0000  0.2579 0.0039


In [123]:
# Eigenvector, eigenvalue and parameters (Problem 2, Training data)

print(result_prob2.min_eigen_solver_result)

{   'aux_operator_eigenvalues': None,
    'cost_function_evals': 102,
    'eigenstate': {   '000000000001': 0.04419417382415922,
                      '000000000011': 0.03125,
                      '000000000100': 0.03125,
                      '000000000101': 0.03125,
                      '000000000110': 0.03125,
                      '000000001001': 0.03125,
                      '000000010001': 0.03125,
                      '000000010011': 0.03125,
                      '000000010100': 0.03125,
                      '000000011000': 0.03125,
                      '000000011001': 0.03125,
                      '000000100010': 0.05412658773652741,
                      '000000100110': 0.04419417382415922,
                      '000000110000': 0.04419417382415922,
                      '000000110010': 0.04419417382415922,
                      '000000111010': 0.03125,
                      '000000111111': 0.03125,
                      '000001000000': 0.04419417382415922,
            

In [124]:
# Mean portfolio return for QAOA Discrete Problem (Problem 2, Training data)

result_prob2_x_adj = np.ndarray(6)
for i in range(6):
    result_prob2_x_adj[i] = result_prob2.x[2*i-1] + result_prob2.x[2*i]

mean_portfolio_return = np.matmul(mu,result_prob2_x_adj)/sum(result_prob2_x_adj)
print(mean_portfolio_return)

0.08996887291403602


In [125]:
# Portfolio variance for QAOA Discrete Problem  (Problem 2, Training data)

portfolio_var = (result_prob2_x_adj.T @ sigma @ result_prob2_x_adj)/sum(result_prob2_x_adj)
print(portfolio_var)

0.1438250125637709


In [126]:
# Code to calculate required funds

price_adj = np.ndarray(num * 2)
for i in range(num * 2 - 1):
    if i % 2 == 0:
        j = int(i / 2)
    else:
        j = int((i+1)/2)
    price_adj[i] = price[j]

# Required fund to construct portfolio and Expected profit
print("Required Funds :", result_prob2.x.T @ price_adj)
print("Profit :", mean_portfolio_return * (result_prob2.x.T @ price_adj))

Required Funds : 98845.9983974359
Profit : 8893.063067879919
