In [9]:
import pandas as pd 
import numpy as np

In [10]:
# Read data and clean data
data = pd.read_csv('final_data.csv', encoding = "CP949")
data = pd.DataFrame(data)
data = data.drop(['Unnamed: 0'], axis = 1)
print(data.head())
print(data.tail())

   경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
0  23679.894737  37084.375000  20734.375000  25632.500000  22607.894737   
1  21847.333333  36286.363636  22288.882353  24075.000000  22393.478261   
2  21751.096774  34916.071429  21576.250000  24533.000000  22645.454545   
3  22952.804878  35281.081081  21809.500000  24554.322581  22978.125000   
4  23099.492647  36368.529412  23075.045455  24375.454545  22335.195122   

   경기도남양주시화도읍84   경기도김포시장기동84  서울특별시송파구잠실동84  서울특별시동작구상도동84  서울특별시강북구미아동84  \
0  20413.157895  30160.000000   86395.652174   49950.000000   33980.000000   
1  21035.000000  26778.571429   82995.000000   47381.250000   35546.153846   
2  20011.764706  29259.200000   84577.500000   49237.500000   35300.000000   
3  20214.285714  28455.714286   84844.680851   49454.166667   31394.444444   
4  20951.470588  30735.652174   85905.737705   55062.185185   32445.833333   

   ...  경기도용인기흥구청덕동84  경기도김포시풍무동84  경기도남양주시오남읍59  서울특별시중랑구신내동84   경기도평택시포승읍59  \

In [11]:
# Use first 6 assets and split data into 70% train data and 30% test data
# 'Geyonggi, Hwaseong, Cheongye-dong' has no contract about first 3 years, so cubicspline works not properly.
data = data.iloc[:, :6]

train_data = data.iloc[:84, :]
test_data = data.iloc[84:, :]
print(train_data.head())
print(test_data.head())

   경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
0  23679.894737  37084.375000  20734.375000  25632.500000  22607.894737   
1  21847.333333  36286.363636  22288.882353  24075.000000  22393.478261   
2  21751.096774  34916.071429  21576.250000  24533.000000  22645.454545   
3  22952.804878  35281.081081  21809.500000  24554.322581  22978.125000   
4  23099.492647  36368.529412  23075.045455  24375.454545  22335.195122   

   경기도남양주시화도읍84  
0  20413.157895  
1  21035.000000  
2  20011.764706  
3  20214.285714  
4  20951.470588  
    경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
84  28281.481481  41628.800000  23401.851852  28242.105263  24562.500000   
85  28391.176471  42962.857143  22767.073171  28183.333333  23976.785714   
86  28764.516129  43739.500000  24052.857143  29339.393939  24313.461538   
87  29745.125000  44037.179487  25175.641026  29346.875000  24514.705882   
88  27933.000000  44150.793651  24551.315789  29794.897959  2

In [12]:
from scipy.interpolate import CubicSpline
import matplotlib.pyplot as plt

In [13]:
# Apply cubicspline to NA imputation
for i in range(6): 
    cs = train_data.iloc[:, i].dropna()
    idx = cs.index.tolist()
    cs = cs.tolist()
    cs = CubicSpline(idx, cs, bc_type='natural')
    train_data.iloc[:, i] = cs(np.arange(84))

print(train_data)

    경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
0   23679.894737  37084.375000  20734.375000  25632.500000  22607.894737   
1   21847.333333  36286.363636  22288.882353  24075.000000  22393.478261   
2   21751.096774  34916.071429  21576.250000  24533.000000  22645.454545   
3   22952.804878  35281.081081  21809.500000  24554.322581  22978.125000   
4   23099.492647  36368.529412  23075.045455  24375.454545  22335.195122   
..           ...           ...           ...           ...           ...   
79  28048.529412  40006.500000  24605.263158  29598.148148  23978.524590   
80  26977.586207  40833.333333  24275.000000  30338.461538  24491.212121   
81  28294.230769  42480.000000  23643.076923  28886.363636  25083.333333   
82  26847.142857  41684.210526  23084.782609  27995.833333  23954.705882   
83  28401.562500  42483.333333  23405.128205  27717.857143  24392.000000   

    경기도남양주시화도읍84  
0   20413.157895  
1   21035.000000  
2   20011.764706  
3   20214.2

C:\Users\Jaeyong\anaconda3\lib\site-packages\pandas\core\indexing.py:1843: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [22]:
train_data_array=np.array(train_data)
print(train_data_array)

# return matrix
r=np.ndarray((83,6))

[[23679.89473684 37084.375      20734.375      25632.5
  22607.89473684 20413.15789474]
 [21847.33333333 36286.36363636 22288.88235294 24075.
  22393.47826087 21035.        ]
 [21751.09677419 34916.07142857 21576.25       24533.
  22645.45454545 20011.76470588]
 [22952.80487805 35281.08108108 21809.5        24554.32258065
  22978.125      20214.28571429]
 [23099.49264706 36368.52941176 23075.04545455 24375.45454545
  22335.19512195 20951.47058824]
 [23357.84090909 35705.17241379 22106.08333333 24690.78378378
  23210.22727273 20730.43478261]
 [23197.35849057 35274.59459459 22642.82352941 25006.25
  22520.375      21001.92307692]
 [22653.84615385 35862.5        22367.35714286 24547.875
  23311.11111111 22210.71428571]
 [22223.68421053 34060.52631579 21961.46875    24744.44444444
  23067.90322581 21119.64285714]
 [22577.         34831.66666667 21709.12121212 24719.51219512
  22136.06896552 20420.55555556]
 [22512.68656716 34920.45454545 21746.875      24232.14285714
  22194.6969697  20903

In [23]:
# print test data
test_data_array=np.array(test_data)
print(test_data_array)

# return matrix
r_test=np.ndarray((35,6))

[[28281.48148148 41628.8        23401.85185185 28242.10526316
  24562.5        23586.25      ]
 [28391.17647059 42962.85714286 22767.07317073 28183.33333333
  23976.78571429 24063.07692308]
 [28764.51612903 43739.5        24052.85714286 29339.39393939
  24313.46153846 24218.97435897]
 [29745.125      44037.17948718 25175.64102564 29346.875
  24514.70588235 24853.375     ]
 [27933.         44150.79365079 24551.31578947 29794.89795918
  24309.25925926 24730.25      ]
 [28797.16981132 44728.87931034 24369.76744186 28547.77777778
  25911.11111111 23977.13043478]
 [27651.36363636 43346.69117647 23953.125      28512.03703704
  25161.53846154 24975.93333333]
 [28143.6746988  46689.27536232 26140.4494382  28997.6744186
  25085.8974359  25304.63414634]
 [29717.15706806 50028.08988764 24997.7539267  30466.51376147
  25394.33962264 24358.89830508]
 [29609.03614458 50763.33333333 24450.45454545 29696.11650485
  25986.32911392 25155.        ]
 [28887.82051282 50441.66666667 25727.55102041 30261.702

In [24]:
# calculate return
# Applied ** 12 for each return to make the return as annual return.
for i in range(r.shape[1]): 
    r[:, i] = ((train_data_array[1:84, i] / train_data_array[0:83, i]) ** 12 ) - 1 
print(r)

[[-6.19614451e-01 -2.29753359e-01  1.38104781e+00 -5.28692927e-01
  -1.08056804e-01  4.33467524e-01]
 [-5.15974597e-02 -3.69938275e-01 -3.22901138e-01  2.53754072e-01
   1.43704534e-01 -4.50314275e-01]
 [ 9.06580950e-01  1.32917101e-01  1.37724009e-01  1.04796661e-02
   1.91248984e-01  1.28433949e-01]
 [ 7.94440025e-02  4.39482115e-01  9.67715346e-01 -8.39963765e-02
  -2.88619497e-01  5.36998137e-01]
 [ 1.42781125e-01 -1.98202441e-01 -4.02372117e-01  1.66771575e-01
   5.85899661e-01 -1.19505212e-01]
 [-7.94019391e-02 -1.35488530e-01  3.33599266e-01  1.64566540e-01
  -3.03766849e-01  1.68982025e-01]
 [-2.47613573e-01  2.19389247e-01 -1.36605883e-01 -1.99089452e-01
   5.13032573e-01  9.57228558e-01]
 [-2.05508371e-01 -4.61321652e-01 -1.97286599e-01  1.00438189e-01
  -1.18257536e-01 -4.53627878e-01]
 [ 2.08376048e-01  3.08202011e-01 -1.29496861e-01 -1.20242962e-02
  -3.90310746e-01 -3.32314722e-01]
 [-3.36529986e-02  3.10211876e-02  2.10696697e-02 -2.12549810e-01
   3.22494212e-02  3.2389

In [25]:
# calculate return
# Applied ** 12 for each return to make the return as annual return.
for i in range(r_test.shape[1]): 
    r_test[:, i] = ((test_data_array[1:36, i] / test_data_array[0:35, i]) ** 12 ) - 1 
print(r_test)

[[ 4.75501009e-02  4.60128777e-01 -2.81074759e-01 -2.46882015e-02
  -2.51450145e-01  2.71473001e-01]
 [ 1.69726163e-01  2.39846458e-01  9.33363978e-01  6.19964041e-01
   1.82142929e-01  8.05753502e-02]
 [ 4.95218653e-01  8.47962459e-02  7.28886116e-01  3.06409644e-03
   1.03973666e-01  3.63815129e-01]
 [-5.29649731e-01  3.14026294e-02 -2.60171905e-01  1.99390162e-01
  -9.60582206e-02 -5.78553035e-02]
 [ 4.41407282e-01  1.68944861e-01 -8.52143395e-02 -4.01361201e-01
   1.15065989e+00 -3.10039244e-01]
 [-3.85671089e-01 -3.13856085e-01 -1.86926975e-01 -1.49205287e-02
  -2.96905239e-01  6.31902651e-01]
 [ 2.35864864e-01  1.43856414e+00  1.85371391e+00  2.24669986e-01
  -3.54840675e-02  1.69876546e-01]
 [ 9.20956316e-01  1.29066434e+00 -4.15135501e-01  8.09318835e-01
   1.57943514e-01 -3.66872824e-01]
 [-4.27968366e-02  1.91336713e-01 -2.33289548e-01 -2.64601459e-01
   3.18548567e-01  4.70957593e-01]
 [-2.56148774e-01 -7.34442599e-02  8.42205736e-01  2.54077352e-01
  -3.04156124e-01 -3.8636

In [26]:
# Adjusted returns to account for current prices

price = train_data_array[train_data_array.shape[0]-1,:]
adj = price / np.mean(price)
r_adj = r * adj
print(r_adj)

[[-6.24607319e-01 -3.46436588e-01  1.14726313e+00 -5.20123468e-01
  -9.35497923e-02  3.48430724e-01]
 [-5.20132332e-02 -5.57816234e-01 -2.68240220e-01  2.49641032e-01
   1.24411687e-01 -3.61972513e-01]
 [ 9.13886200e-01  2.00420777e-01  1.14409998e-01  1.03098037e-02
   1.65573125e-01  1.03238031e-01]
 [ 8.00841641e-02  6.62678816e-01  8.03899854e-01 -8.26348990e-02
  -2.49871298e-01  4.31650906e-01]
 [ 1.43931659e-01 -2.98862125e-01 -3.34258300e-01  1.64068414e-01
   5.07240539e-01 -9.60609164e-02]
 [-8.00417617e-02 -2.04298141e-01  2.77127362e-01  1.61899120e-01
  -2.62985064e-01  1.35831466e-01]
 [-2.49608848e-01  3.30808926e-01 -1.13481149e-01 -1.95862458e-01
   4.44156118e-01  7.69441356e-01]
 [-2.07164362e-01 -6.95609846e-01 -1.63889793e-01  9.88102097e-02
  -1.02381039e-01 -3.64636059e-01]
 [ 2.10055147e-01  4.64726406e-01 -1.07575547e-01 -1.18293973e-02
  -3.37910134e-01 -2.67121878e-01]
 [-3.39241753e-02  4.67757008e-02  1.75029821e-02 -2.09104640e-01
   2.79198212e-02  2.6035

In [27]:
# Adjusted returns to account for current prices

price_test = test_data_array[test_data_array.shape[0]-1,:]
adj_test = price_test / np.mean(price_test)
r_adj_test = r_test * adj_test
print(r_adj_test)

[[ 4.35601856e-02  6.17559433e-01 -2.57381652e-01 -2.44319073e-02
  -2.24291374e-01  2.56392523e-01]
 [ 1.55484490e-01  3.21908669e-01  8.54686362e-01  6.13528043e-01
   1.62469931e-01  7.60993440e-02]
 [ 4.53664998e-01  1.13808838e-01  6.67444895e-01  3.03228730e-03
   9.27436186e-02  3.43604993e-01]
 [-4.85206975e-01  4.21468749e-02 -2.38240798e-01  1.97320244e-01
  -8.56831094e-02 -5.46414087e-02]
 [ 4.04368924e-01  2.26748462e-01 -7.80312241e-02 -3.97194573e-01
   1.02637875e+00 -2.92816388e-01]
 [-3.53309539e-01 -4.21240304e-01 -1.71170025e-01 -1.47656351e-02
  -2.64836928e-01  5.96800101e-01]
 [ 2.16073511e-01  1.93076134e+00  1.69745569e+00  2.22337632e-01
  -3.16514841e-02  1.60439808e-01]
 [ 8.43679136e-01  1.73225840e+00 -3.80141787e-01  8.00917099e-01
   1.40884261e-01 -3.46492831e-01]
 [-3.92057664e-02  2.56801570e-01 -2.13624481e-01 -2.61854566e-01
   2.84142591e-01  4.44795632e-01]
 [-2.34655404e-01 -9.85728295e-02  7.71212274e-01  2.51439713e-01
  -2.71304655e-01 -3.6489

In [39]:
# Calculate return and covariance matrix for training data
mu = np.mean(r_adj,axis = 0)
sigma = np.cov(r_adj.T)
c = np.array([0.015,0.017058333,0.015,0.015325,0.015,0.015001884])

In [29]:
print(mu)

[0.11140197 0.09647029 0.07731924 0.07104768 0.05040973 0.12074455]


In [30]:
print(sigma)

[[ 0.19058299  0.05754072 -0.00293819  0.00600126  0.01083507 -0.04702808]
 [ 0.05754072  0.22245443  0.03711413 -0.01211019 -0.00709406 -0.03075613]
 [-0.00293819  0.03711413  0.12424921  0.02968338 -0.01820187  0.00782663]
 [ 0.00600126 -0.01211019  0.02968338  0.14948229  0.01364413 -0.05016642]
 [ 0.01083507 -0.00709406 -0.01820187  0.01364413  0.0815112  -0.01607576]
 [-0.04702808 -0.03075613  0.00782663 -0.05016642 -0.01607576  0.31012103]]


In [31]:
# Calculate return and covariance matrix for test data
mu_test = np.mean(r_adj_test,axis = 0)
sigma_test = np.cov(r_adj_test.T)

In [32]:
print(mu_test)

[0.45220507 0.44625879 1.66319004 0.61237206 0.5127338  0.71951957]


In [33]:
print(sigma_test)

[[ 1.06635832  0.33291448 -1.09116013  0.07349856 -0.06815442 -0.28920297]
 [ 0.33291448  0.73080592 -1.8732482   0.06631569 -0.17120678 -0.51588203]
 [-1.09116013 -1.8732482  57.43151902 -1.61793834 -1.54181997  1.87927482]
 [ 0.07349856  0.06631569 -1.61793834  1.94264081  0.1567196  -0.32871428]
 [-0.06815442 -0.17120678 -1.54181997  0.1567196   1.33917173  0.72822192]
 [-0.28920297 -0.51588203  1.87927482 -0.32871428  0.72822192  2.34482689]]


In [34]:
from qiskit import Aer
from qiskit.algorithms import VQE, QAOA, NumPyMinimumEigensolver
from qiskit.algorithms.optimizers import COBYLA
from qiskit.circuit.library import TwoLocal
from qiskit.utils import QuantumInstance
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit_optimization.applications import OptimizationApplication
from qiskit_optimization.converters import QuadraticProgramToQubo
import qiskit_optimization
import numpy as np
import matplotlib.pyplot as plt
import datetime

In [35]:
# Set number of assets and risk appetite

num = 6
q = 0.5

In [36]:
# Code to display results

def index_to_selection(i, num_assets):
    s = "{0:b}".format(i).rjust(num_assets)
    x = np.array([1 if s[i] == "1" else 0 for i in reversed(range(num_assets))])
    return x

In [108]:
# Code to display results

def print_result(result, problem):
    selection = result.x
    value = result.fval
    print("Optimal: selection {}, value {:.4f}".format(selection, value))
    
    list_a = list(result.min_eigen_solver_result.eigenstate.keys())
    selection = np.ndarray(np.size(list_a))
    value = np.ndarray(np.size(list_a))
    for i in range(np.size(list_a)):
        value[i] = QuadraticProgramToQubo().convert(problem).objective.evaluate(index_to_selection(int(list_a[i],2),num))
        selection[i] = list_a[i][::-1]
    probabilities = np.square(list(result.min_eigen_solver_result.eigenstate.values()))
    
    d = {'selection': selection, 'value': value, 'prob':probabilities}
    df = pd.DataFrame(d)
    df_sorted = df.sort_values(by = 'prob',ascending = False)
    
    print("\n----------------- Full result ---------------------")
    print(df_sorted.head(10))

In [41]:
# Simple quadratic problem (Problem 3, Training data)

qp3 = qiskit_optimization.QuadraticProgram()

for i in range(num): 
    qp3.binary_var(name="x%d" % i)

qp3.minimize(quadratic = q * sigma, linear = -1 * mu + c)
print(qp3.export_as_lp_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: CPLEX

Minimize
 obj: - 0.096401971254 x0 - 0.079411960894 x1 - 0.062319244025 x2
      - 0.055722677340 x3 - 0.035409729773 x4 - 0.105742662605 x5 + [
      0.190582991451 x0^2 + 0.115081443944 x0*x1 - 0.005876372512 x0*x2
      + 0.012002518106 x0*x3 + 0.021670146828 x0*x4 - 0.094056161178 x0*x5
      + 0.222454433080 x1^2 + 0.074228258467 x1*x2 - 0.024220386390 x1*x3
      - 0.014188119424 x1*x4 - 0.061512251906 x1*x5 + 0.124249207446 x2^2
      + 0.059366763870 x2*x3 - 0.036403730514 x2*x4 + 0.015653263482 x2*x5
      + 0.149482291718 x3^2 + 0.027288259061 x3*x4 - 0.100332833638 x3*x5
      + 0.081511201905 x4^2 - 0.032151525039 x4*x5 + 0.310121028387 x5^2 ]/2
Subject To

Bounds
 0 <= x0 <= 1
 0 <= x1 <= 1
 0 <= x2 <= 1
 0 <= x3 <= 1
 0 <= x4 <= 1
 0 <= x5 <= 1

Binaries
 x0 x1 x2 x3 x4 x5
End



In [45]:
# Result of binary quadratic problem with qasm simulator and QAOA (Problem 3, Training data)

backend = Aer.get_backend("qasm_simulator")

cobyla = COBYLA()
cobyla.set_options(maxiter=250)
quantum_instance = QuantumInstance(backend=backend)
qaoa_mes = QAOA(optimizer=cobyla, reps=10, quantum_instance=quantum_instance)
qaoa = MinimumEigenOptimizer(qaoa_mes)
result_prob3 = qaoa.solve(qp3)

print(result_prob3)

optimal function value: -0.023967393775162826
optimal value: [1. 0. 0. 1. 0. 1.]
status: SUCCESS


In [46]:
# Result for QAOA (Problem 3, Training data)

print_result(result_prob3, qp3)

Optimal: selection [1. 0. 0. 1. 0. 1.], value -0.0240

----------------- Full result ---------------------
    selection     value      prob
28   100101.0 -0.023967  0.073242
38   101011.0 -0.012224  0.064453
41   100111.0 -0.010218  0.054688
22   100001.0  0.001179  0.050781
34   100011.0  0.001284  0.050781
0         0.0  0.000000  0.050781
10       10.0  0.005346  0.046875
14     1010.0 -0.013051  0.045898
1    100000.0 -0.001110  0.044922
27      101.0  0.018170  0.036133
29    10101.0  0.007119  0.035156
42    10111.0  0.002939  0.034180
3      1000.0 -0.000195  0.033203
40      111.0  0.021084  0.030273
4    101000.0 -0.004243  0.028320
45   101111.0  0.005957  0.025391
26   101001.0  0.005873  0.024414
5       100.0  0.019018  0.023437
37     1011.0  0.028018  0.019531
35    10011.0  0.032553  0.017578
32   101101.0  0.010410  0.017578
17      110.0  0.038008  0.016602
15   101010.0 -0.006264  0.015625
11   100010.0  0.015070  0.015625
44     1111.0  0.040198  0.014648
23    100

In [47]:
# Eigenvector, eigenvalue and parameters (Problem 1, Training data)

print(result_prob3.min_eigen_solver_result)

{   'aux_operator_eigenvalues': None,
    'cost_function_evals': 230,
    'eigenstate': {   '000000': 0.22534695471649932,
                      '000001': 0.21194781197266463,
                      '000010': 0.12103072956898178,
                      '000100': 0.18221724671391565,
                      '000101': 0.16828640022295324,
                      '001000': 0.15309310892394862,
                      '001001': 0.09882117688026186,
                      '001010': 0.05412658773652741,
                      '001100': 0.0625,
                      '001101': 0.04419417382415922,
                      '010000': 0.21650635094610965,
                      '010001': 0.125,
                      '010010': 0.11692679333668567,
                      '010011': 0.03125,
                      '010100': 0.21423920626253262,
                      '010101': 0.125,
                      '010111': 0.03125,
                      '011000': 0.1288470508005519,
                      '011011': 0.03125,
 

In [48]:
# Mean portfolio return for QAOA (Problem 3, Training data)

mean_portfolio_return = np.matmul(mu,result_prob3.x)/sum(result_prob3.x) - np.matmul(c,result_prob3.x)/sum(result_prob3.x)
print(mean_portfolio_return)

0.08595577039939456


In [49]:
# Portfolio variance for QAOA (Problem 3, Training data)

portfolio_var = (result_prob3.x.T @ sigma @ result_prob3.x)/sum(result_prob3.x)
print(portfolio_var)

0.15593327828201387


In [54]:
# Required fund to construct portfolio and Expected profit (Problem 3, Training data)

print("Required Funds :", result_prob3.x.T @ (price * (np.array([1] * num + c))))
print("Profit :", mean_portfolio_return * (result_prob3.x.T @ price))

Required Funds : 79957.27921629138
Profit : 6770.454729933142


In [63]:
# Problem 3 using VQE
from qiskit.utils import algorithm_globals

backend = Aer.get_backend("qasm_simulator")

cobyla = COBYLA()
cobyla.set_options(maxiter=250)
ry = TwoLocal(num, "ry", "cz", reps=10, entanglement="full")
quantum_instance = QuantumInstance(backend=backend)
vqe_mes = VQE(ry, optimizer=cobyla, quantum_instance=quantum_instance)
vqe = MinimumEigenOptimizer(vqe_mes)
result_prob3_vqe = vqe.solve(qp3)

print(result_prob3_vqe)

optimal function value: -0.023967393775162826
optimal value: [1. 0. 0. 1. 0. 1.]
status: SUCCESS


In [109]:
print_result(result_prob3_vqe, qp3)

Optimal: selection [1. 0. 0. 1. 0. 1.], value -0.0240

----------------- Full result ---------------------
    selection     value      prob
40   100111.0 -0.010218  0.173828
23   100001.0  0.001179  0.162109
0         0.0  0.000000  0.088867
30   100101.0 -0.023967  0.075195
1    100000.0 -0.001110  0.068359
42   110111.0  0.029178  0.063477
38   101011.0 -0.012224  0.043945
39      111.0  0.021084  0.034180
37   110011.0  0.052790  0.029297
36   100011.0  0.001284  0.029297


In [65]:
print(result_prob3_vqe.min_eigen_solver_result)

{   'aux_operator_eigenvalues': None,
    'cost_function_evals': 250,
    'eigenstate': {   '000000': 0.2981060004427955,
                      '000001': 0.2614562582918986,
                      '000011': 0.09375,
                      '000100': 0.13621559198564606,
                      '000101': 0.05412658773652741,
                      '000110': 0.08838834764831845,
                      '000111': 0.05412658773652741,
                      '001001': 0.09882117688026186,
                      '001010': 0.0625,
                      '001011': 0.10825317547305482,
                      '001100': 0.08267972847076846,
                      '001101': 0.07654655446197431,
                      '001110': 0.07654655446197431,
                      '001111': 0.04419417382415922,
                      '010011': 0.06987712429686843,
                      '010100': 0.09375,
                      '010101': 0.04419417382415922,
                      '010110': 0.07654655446197431,
               

In [67]:
# Simple quadratic problem (Problem 3, Test data)

qp3_test = qiskit_optimization.QuadraticProgram()

for i in range(num): 
    qp3_test.binary_var(name="x%d" % i)

qp3_test.minimize(quadratic = q * sigma_test, linear = -1 * mu_test + c)
print(qp3_test.export_as_lp_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: CPLEX

Minimize
 obj: - 0.437205070146 x0 - 0.429200458292 x1 - 1.648190042914 x2
      - 0.597047059606 x3 - 0.497733795204 x4 - 0.704517687626 x5 + [
      1.066358316167 x0^2 + 0.665828962347 x0*x1 - 2.182320254993 x0*x2
      + 0.146997110873 x0*x3 - 0.136308833940 x0*x4 - 0.578405942314 x0*x5
      + 0.730805915288 x1^2 - 3.746496393593 x1*x2 + 0.132631375944 x1*x3
      - 0.342413556556 x1*x4 - 1.031764061020 x1*x5 + 57.431519017861 x2^2
      - 3.235876679741 x2*x3 - 3.083639930293 x2*x4 + 3.758549647920 x2*x5
      + 1.942640814050 x3^2 + 0.313439195676 x3*x4 - 0.657428553208 x3*x5
      + 1.339171733157 x4^2 + 1.456443830801 x4*x5 + 2.344826887236 x5^2 ]/2
Subject To

Bounds
 0 <= x0 <= 1
 0 <= x1 <= 1
 0 <= x2 <= 1
 0 <= x3 <= 1
 0 <= x4 <= 1
 0 <= x5 <= 1

Binaries
 x0 x1 x2 x3 x4 x5
End



In [99]:
# Result of binary quadratic problem with qasm simulator and QAOA (Problem 3, Test data)

backend = Aer.get_backend("qasm_simulator")

cobyla = COBYLA()
cobyla.set_options(maxiter=250)
quantum_instance = QuantumInstance(backend=backend)
qaoa_mes = QAOA(optimizer=cobyla, reps=10, quantum_instance=quantum_instance)
qaoa = MinimumEigenOptimizer(qaoa_mes)
result_prob3_test = qaoa.solve(qp3_test)

print(result_prob3_test)

optimal function value: -0.1117837751662143
optimal value: [0. 1. 0. 0. 0. 1.]
status: SUCCESS


In [110]:
print_result(result_prob3_test, qp3_test)

Optimal: selection [0. 1. 0. 0. 0. 1.], value -0.1118

----------------- Full result ---------------------
    selection      value      prob
30   100001.0   0.274667  0.090820
8    100100.0   0.543746  0.080078
23   100110.0   0.804163  0.072266
0         0.0   0.000000  0.056641
54   110111.0   1.030708  0.049805
51      111.0   1.570248  0.039063
22      110.0   0.702845  0.038086
58   111111.0  23.853385  0.035156
50    11011.0  26.148860  0.031250
52   100111.0   1.382364  0.029297


In [111]:
print(result_prob3_test.min_eigen_solver_result)

{   'aux_operator_eigenvalues': None,
    'cost_function_evals': 172,
    'eigenstate': {   '000000': 0.23799290955824715,
                      '000001': 0.13975424859373686,
                      '000011': 0.10364452469860624,
                      '000100': 0.13258252147247765,
                      '000101': 0.05412658773652741,
                      '000110': 0.06987712429686843,
                      '000111': 0.06987712429686843,
                      '001000': 0.03125,
                      '001001': 0.2829807855667943,
                      '001010': 0.14320549046737,
                      '001011': 0.0625,
                      '001100': 0.09882117688026186,
                      '001101': 0.08267972847076846,
                      '001110': 0.13621559198564606,
                      '001111': 0.11692679333668567,
                      '010000': 0.09882117688026186,
                      '010001': 0.14986973510352247,
                      '010010': 0.07654655446197431,
     

In [102]:
# Mean portfolio return for QAOA (Problem 3, Test data)

mean_portfolio_return = np.matmul(mu_test,result_prob3_test.x)/sum(result_prob3_test.x) - np.matmul(c,result_prob3_test.x)/sum(result_prob3_test.x)
print(mean_portfolio_return)

0.5668590729588698


In [103]:
# Portfolio variance for QAOA (Problem 3, Test data)

portfolio_var = (result_prob3_test.x.T @ sigma_test @ result_prob3_test.x)/sum(result_prob3_test.x)
print(portfolio_var)

1.0219343707515254


In [104]:
# Required fund to construct portfolio and Expected profit (Problem 3, Test data)

print("Required Funds :", result_prob3_test.x.T @ (price * (np.array([1] * num + c))))
print("Profit :", mean_portfolio_return * (result_prob3_test.x.T @ price))

Required Funds : 66195.0881555033
Profit : 36919.894793011794
