In [10]:
import pandas as pd 
import numpy as np

In [12]:
# Read data and clean data
data = pd.read_csv('final_data.csv', encoding = "CP949")
data = pd.DataFrame(data)
data = data.drop(['Unnamed: 0'], axis = 1)
print(data.head())
print(data.tail())

   경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
0  23679.894737  37084.375000  20734.375000  25632.500000  22607.894737   
1  21847.333333  36286.363636  22288.882353  24075.000000  22393.478261   
2  21751.096774  34916.071429  21576.250000  24533.000000  22645.454545   
3  22952.804878  35281.081081  21809.500000  24554.322581  22978.125000   
4  23099.492647  36368.529412  23075.045455  24375.454545  22335.195122   

   경기도남양주시화도읍84   경기도김포시장기동84  서울특별시송파구잠실동84  서울특별시동작구상도동84  서울특별시강북구미아동84  \
0  20413.157895  30160.000000   86395.652174   49950.000000   33980.000000   
1  21035.000000  26778.571429   82995.000000   47381.250000   35546.153846   
2  20011.764706  29259.200000   84577.500000   49237.500000   35300.000000   
3  20214.285714  28455.714286   84844.680851   49454.166667   31394.444444   
4  20951.470588  30735.652174   85905.737705   55062.185185   32445.833333   

   ...  경기도용인기흥구청덕동84  경기도김포시풍무동84  경기도남양주시오남읍59  서울특별시중랑구신내동84   경기도평택시포승읍59  \

In [13]:
# Use first 6 assets and split data into 70% train data and 30% test data
# 'Geyonggi, Hwaseong, Cheongye-dong' has no contract about first 3 years, so cubicspline works not properly.
data = data.iloc[:, :6]

train_data = data.iloc[:84, :]
test_data = data.iloc[84:, :]
print(train_data.head())
print(test_data.head())

   경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
0  23679.894737  37084.375000  20734.375000  25632.500000  22607.894737   
1  21847.333333  36286.363636  22288.882353  24075.000000  22393.478261   
2  21751.096774  34916.071429  21576.250000  24533.000000  22645.454545   
3  22952.804878  35281.081081  21809.500000  24554.322581  22978.125000   
4  23099.492647  36368.529412  23075.045455  24375.454545  22335.195122   

   경기도남양주시화도읍84  
0  20413.157895  
1  21035.000000  
2  20011.764706  
3  20214.285714  
4  20951.470588  
    경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
84  28281.481481  41628.800000  23401.851852  28242.105263  24562.500000   
85  28391.176471  42962.857143  22767.073171  28183.333333  23976.785714   
86  28764.516129  43739.500000  24052.857143  29339.393939  24313.461538   
87  29745.125000  44037.179487  25175.641026  29346.875000  24514.705882   
88  27933.000000  44150.793651  24551.315789  29794.897959  2

In [14]:
from scipy.interpolate import CubicSpline
import matplotlib.pyplot as plt

In [15]:
# Apply cubicspline to NA imputation
for i in range(6): 
    cs = train_data.iloc[:, i].dropna()
    idx = cs.index.tolist()
    cs = cs.tolist()
    cs = CubicSpline(idx, cs, bc_type='natural')
    train_data.iloc[:, i] = cs(np.arange(84))

print(train_data)

    경기도남양주시진접읍84   경기도화성시반송동84   경기도화성시봉담읍84  경기도남양주시호평동84   경기도화성시향남읍84  \
0   23679.894737  37084.375000  20734.375000  25632.500000  22607.894737   
1   21847.333333  36286.363636  22288.882353  24075.000000  22393.478261   
2   21751.096774  34916.071429  21576.250000  24533.000000  22645.454545   
3   22952.804878  35281.081081  21809.500000  24554.322581  22978.125000   
4   23099.492647  36368.529412  23075.045455  24375.454545  22335.195122   
..           ...           ...           ...           ...           ...   
79  28048.529412  40006.500000  24605.263158  29598.148148  23978.524590   
80  26977.586207  40833.333333  24275.000000  30338.461538  24491.212121   
81  28294.230769  42480.000000  23643.076923  28886.363636  25083.333333   
82  26847.142857  41684.210526  23084.782609  27995.833333  23954.705882   
83  28401.562500  42483.333333  23405.128205  27717.857143  24392.000000   

    경기도남양주시화도읍84  
0   20413.157895  
1   21035.000000  
2   20011.764706  
3   20214.2

C:\Users\Jaeyong\anaconda3\lib\site-packages\pandas\core\indexing.py:1843: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [16]:
train_data_array=np.array(train_data)
print(train_data_array)

# return matrix
r=np.ndarray((83,6))

[[23679.89473684 37084.375      20734.375      25632.5
  22607.89473684 20413.15789474]
 [21847.33333333 36286.36363636 22288.88235294 24075.
  22393.47826087 21035.        ]
 [21751.09677419 34916.07142857 21576.25       24533.
  22645.45454545 20011.76470588]
 [22952.80487805 35281.08108108 21809.5        24554.32258065
  22978.125      20214.28571429]
 [23099.49264706 36368.52941176 23075.04545455 24375.45454545
  22335.19512195 20951.47058824]
 [23357.84090909 35705.17241379 22106.08333333 24690.78378378
  23210.22727273 20730.43478261]
 [23197.35849057 35274.59459459 22642.82352941 25006.25
  22520.375      21001.92307692]
 [22653.84615385 35862.5        22367.35714286 24547.875
  23311.11111111 22210.71428571]
 [22223.68421053 34060.52631579 21961.46875    24744.44444444
  23067.90322581 21119.64285714]
 [22577.         34831.66666667 21709.12121212 24719.51219512
  22136.06896552 20420.55555556]
 [22512.68656716 34920.45454545 21746.875      24232.14285714
  22194.6969697  20903

In [17]:
# calculate return
# Applied ** 12 for each return to make the return as annual return.
for i in range(r.shape[1]): 
    r[:, i] = ((train_data_array[1:84, i] / train_data_array[0:83, i]) ** 12 ) - 1 
print(r)

[[-6.19614451e-01 -2.29753359e-01  1.38104781e+00 -5.28692927e-01
  -1.08056804e-01  4.33467524e-01]
 [-5.15974597e-02 -3.69938275e-01 -3.22901138e-01  2.53754072e-01
   1.43704534e-01 -4.50314275e-01]
 [ 9.06580950e-01  1.32917101e-01  1.37724009e-01  1.04796661e-02
   1.91248984e-01  1.28433949e-01]
 [ 7.94440025e-02  4.39482115e-01  9.67715346e-01 -8.39963765e-02
  -2.88619497e-01  5.36998137e-01]
 [ 1.42781125e-01 -1.98202441e-01 -4.02372117e-01  1.66771575e-01
   5.85899661e-01 -1.19505212e-01]
 [-7.94019391e-02 -1.35488530e-01  3.33599266e-01  1.64566540e-01
  -3.03766849e-01  1.68982025e-01]
 [-2.47613573e-01  2.19389247e-01 -1.36605883e-01 -1.99089452e-01
   5.13032573e-01  9.57228558e-01]
 [-2.05508371e-01 -4.61321652e-01 -1.97286599e-01  1.00438189e-01
  -1.18257536e-01 -4.53627878e-01]
 [ 2.08376048e-01  3.08202011e-01 -1.29496861e-01 -1.20242962e-02
  -3.90310746e-01 -3.32314722e-01]
 [-3.36529986e-02  3.10211876e-02  2.10696697e-02 -2.12549810e-01
   3.22494212e-02  3.2389

In [18]:
# Adjusted returns to account for current prices

price = train_data_array[train_data_array.shape[0]-1,:]
adj = price / np.mean(price)
r_adj = r * adj
print(r_adj)

[[-6.24607319e-01 -3.46436588e-01  1.14726313e+00 -5.20123468e-01
  -9.35497923e-02  3.48430724e-01]
 [-5.20132332e-02 -5.57816234e-01 -2.68240220e-01  2.49641032e-01
   1.24411687e-01 -3.61972513e-01]
 [ 9.13886200e-01  2.00420777e-01  1.14409998e-01  1.03098037e-02
   1.65573125e-01  1.03238031e-01]
 [ 8.00841641e-02  6.62678816e-01  8.03899854e-01 -8.26348990e-02
  -2.49871298e-01  4.31650906e-01]
 [ 1.43931659e-01 -2.98862125e-01 -3.34258300e-01  1.64068414e-01
   5.07240539e-01 -9.60609164e-02]
 [-8.00417617e-02 -2.04298141e-01  2.77127362e-01  1.61899120e-01
  -2.62985064e-01  1.35831466e-01]
 [-2.49608848e-01  3.30808926e-01 -1.13481149e-01 -1.95862458e-01
   4.44156118e-01  7.69441356e-01]
 [-2.07164362e-01 -6.95609846e-01 -1.63889793e-01  9.88102097e-02
  -1.02381039e-01 -3.64636059e-01]
 [ 2.10055147e-01  4.64726406e-01 -1.07575547e-01 -1.18293973e-02
  -3.37910134e-01 -2.67121878e-01]
 [-3.39241753e-02  4.67757008e-02  1.75029821e-02 -2.09104640e-01
   2.79198212e-02  2.6035

In [19]:
# Calculate return and covariance matrix for training data
mu = np.mean(r_adj,axis = 0)
sigma = np.cov(r_adj.T)

In [20]:
print(mu)

[0.11140197 0.09647029 0.07731924 0.07104768 0.05040973 0.12074455]


In [21]:
print(sigma)

[[ 0.19058299  0.05754072 -0.00293819  0.00600126  0.01083507 -0.04702808]
 [ 0.05754072  0.22245443  0.03711413 -0.01211019 -0.00709406 -0.03075613]
 [-0.00293819  0.03711413  0.12424921  0.02968338 -0.01820187  0.00782663]
 [ 0.00600126 -0.01211019  0.02968338  0.14948229  0.01364413 -0.05016642]
 [ 0.01083507 -0.00709406 -0.01820187  0.01364413  0.0815112  -0.01607576]
 [-0.04702808 -0.03075613  0.00782663 -0.05016642 -0.01607576  0.31012103]]


In [22]:
from qiskit import Aer
from qiskit.algorithms import VQE, QAOA, NumPyMinimumEigensolver
from qiskit.algorithms.optimizers import COBYLA
from qiskit.circuit.library import TwoLocal
from qiskit.utils import QuantumInstance
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit_optimization.applications import OptimizationApplication
from qiskit_optimization.converters import QuadraticProgramToQubo
import qiskit_optimization
import numpy as np
import matplotlib.pyplot as plt
import datetime

In [23]:
# Set number of assets and risk appetite

num = 6
q = 0.5

In [83]:
# Code to display results

def index_to_selection(i, num_assets):
    s = "{0:b}".format(i).rjust(num_assets)
    x = np.array([1 if s[i] == "1" else 0 for i in reversed(range(num_assets))])
    return x

In [100]:
# Code to display results

def print_result(result, problem):
    selection = result.x
    value = result.fval
    print("Optimal: selection {}, value {:.4f}".format(selection, value))
    
    list_a = list(result.min_eigen_solver_result.eigenstate.keys())
    selection = np.ndarray(np.size(list_a))
    value = np.ndarray(np.size(list_a))
    for i in range(np.size(list_a)):
        value[i] = QuadraticProgramToQubo().convert(problem).objective.evaluate(index_to_selection(int(list_a[i],2),num))
        selection[i] = list_a[i][::-1]
    probabilities = np.square(list(result.min_eigen_solver_result.eigenstate.values()))
    
    d = {'selection': selection, 'value': value, 'prob':probabilities}
    df = pd.DataFrame(d)
    df_sorted = df.sort_values(by = 'prob',ascending = False)
    
    print("\n----------------- Full result ---------------------")
    print(df_sorted)

In [28]:
# Simple quadratic problem (Problem 1, Training data)

qp = qiskit_optimization.QuadraticProgram()

for i in range(num): 
    qp.binary_var(name="x%d" % i)

qp.minimize(quadratic = q * sigma, linear = -1 * mu)
print(qp.export_as_lp_string())

\ This file has been generated by DOcplex
\ ENCODING=ISO-8859-1
\Problem name: CPLEX

Minimize
 obj: - 0.111401971254 x0 - 0.096470293894 x1 - 0.077319244025 x2
      - 0.071047677340 x3 - 0.050409729773 x4 - 0.120744546605 x5 + [
      0.190582991451 x0^2 + 0.115081443944 x0*x1 - 0.005876372512 x0*x2
      + 0.012002518106 x0*x3 + 0.021670146828 x0*x4 - 0.094056161178 x0*x5
      + 0.222454433080 x1^2 + 0.074228258467 x1*x2 - 0.024220386390 x1*x3
      - 0.014188119424 x1*x4 - 0.061512251906 x1*x5 + 0.124249207446 x2^2
      + 0.059366763870 x2*x3 - 0.036403730514 x2*x4 + 0.015653263482 x2*x5
      + 0.149482291718 x3^2 + 0.027288259061 x3*x4 - 0.100332833638 x3*x5
      + 0.081511201905 x4^2 - 0.032151525039 x4*x5 + 0.310121028387 x5^2 ]/2
Subject To

Bounds
 0 <= x0 <= 1
 0 <= x1 <= 1
 0 <= x2 <= 1
 0 <= x3 <= 1
 0 <= x4 <= 1
 0 <= x5 <= 1

Binaries
 x0 x1 x2 x3 x4 x5
End



In [112]:
# Result of binary quadratic problem with qasm simulator and QAOA (Problem 1, Training data)

backend = Aer.get_backend("qasm_simulator")

cobyla = COBYLA()
cobyla.set_options(maxiter=1000)
quantum_instance = QuantumInstance(backend=backend)
qaoa_mes = QAOA(optimizer=cobyla, reps=10, quantum_instance=quantum_instance)
qaoa = MinimumEigenOptimizer(qaoa_mes)
result_prob1 = qaoa.solve(qp)

print(result_prob1)

optimal function value: -0.07222546652860223
optimal value: [1. 0. 1. 0. 1. 1.]
status: SUCCESS


In [113]:
# Result for QAOA (Problem 1, Training data)

print_result(result_prob1, qp)

Optimal: selection [1. 0. 1. 0. 1. 1.], value -0.0722

----------------- Full result ---------------------
selection		value		probability
---------------------------------------------------
    selection     value      prob
53   101011.0 -0.072225  0.037109
41   100101.0 -0.069294  0.030273
5    101000.0 -0.034243  0.027344
58    10111.0 -0.059446  0.026367
57   100111.0 -0.070545  0.026367
..        ...       ...       ...
19   110010.0  0.050274  0.003906
3    110000.0  0.056187  0.003906
15   111100.0  0.102436  0.002930
11   110100.0  0.053772  0.002930
31   111110.0  0.091966  0.001953

[64 rows x 3 columns]


In [114]:
# Eigenvector, eigenvalue and parameters (Problem 1, Training data)

print(result_prob1.min_eigen_solver_result)

{   'aux_operator_eigenvalues': None,
    'cost_function_evals': 157,
    'eigenstate': {   '000000': 0.11692679333668567,
                      '000001': 0.10825317547305482,
                      '000010': 0.11267347735824966,
                      '000011': 0.0625,
                      '000100': 0.15309310892394862,
                      '000101': 0.16535945694153692,
                      '000110': 0.09882117688026186,
                      '000111': 0.07654655446197431,
                      '001000': 0.11692679333668567,
                      '001001': 0.12103072956898178,
                      '001010': 0.09375,
                      '001011': 0.05412658773652741,
                      '001100': 0.12103072956898178,
                      '001101': 0.09375,
                      '001110': 0.09882117688026186,
                      '001111': 0.05412658773652741,
                      '010000': 0.11267347735824966,
                      '010001': 0.10364452469860624,
             

In [115]:
# Mean portfolio return for QAOA (Problem 1, Training data)

mean_portfolio_return = np.matmul(mu,result_prob1.x)/sum(result_prob1.x)
print(mean_portfolio_return)

0.08996887291403602


In [116]:
# Portfolio variance for QAOA (Problem 1, Training data)

portfolio_var = (result_prob1.x.T @ sigma @ result_prob1.x)/sum(result_prob1.x)
print(portfolio_var)

0.1438250125637709


In [137]:
# Required fund to construct portfolio and Expected profit

print("Required Funds :", result_prob1.x.T @ price)
print("Profit :", mean_portfolio_return * (result_prob1.x.T @ price))

Required Funds : 98845.9983974359
Profit : 8893.063067879919


In [131]:
# Code for Grid Search

gridsearch = np.ndarray(2 ** num)
index = np.ndarray(2 ** num)

for i in range(2 ** num):
    gridsearch[i] = QuadraticProgramToQubo().convert(qp).objective.evaluate(index_to_selection(i,num))

for i in range(2 ** num):
    index[i] = gridsearch.argsort()[i]

# Results (compare with results from above)
print(format(int(index[0]),"b")[::-1])
print(sorted(gridsearch)[0])

101011
-0.07222546652860223
